serve:
  port: 8080

#?????????
spring:
  application:
  #????????
  datasource:
    # type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/strictTeach
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#Mybatis?????
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????
    map-underscore-to-camel-case: true

